name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instala Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm install

      # 4. Build del proyecto
      - name: Build project
        run: npm run build

      # 5. Deploy manual usando git
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Crear rama gh-pages si no existe
          git checkout --orphan gh-pages

          # Borrar todo
          git rm -rf .

          # Copiar contenido de dist
          cp -r dist/* .

          # Agregar archivos
          git add .

          git commit -m "Deploy to GitHub Pages"

          git push origin gh-pages --force
